[package]
name = "hybridx"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "d9cfa0077ebf55c4a95228eff5ebbda1c9c36e1c" }

[addresses]
Sender = "0xF8FFC1B4CED065A3D41DD8B892945FC9DEBFFFC4390AD80CC76FC026A1108A6A"
TestUser = "0xC79DB1632B379BD33525E9A27B3974BD0DA1D4690C373877A32D907DB69E596D"

